"""Version and build provenance for the CortexLume science sidecar.

The generated ``_build_version.py`` is produced from the repository root
``package.json`` during release builds. Source checkouts and editable installs
fall back to package metadata, while runtime environment variables let the
desktop process pass the exact application build identity to a packaged
sidecar.
"""

from __future__ import annotations

import os
import json
import hashlib
from importlib.metadata import PackageNotFoundError, version as distribution_version
from pathlib import Path

try:  # Generated by scripts/generate-version-metadata.mjs for release builds.
    from ._build_version import (  # type: ignore[import-not-found]
        APPLICATION_VERSION as _GENERATED_APPLICATION_VERSION,
        DEPENDENCY_LOCK_SHA256 as _GENERATED_DEPENDENCY_LOCK_SHA256,
        GIT_COMMIT as _GENERATED_GIT_COMMIT,
        SCIENCE_API_VERSION as _GENERATED_SCIENCE_API_VERSION,
        SIDECAR_PACKAGE_VERSION as _GENERATED_SIDECAR_PACKAGE_VERSION,
    )
except ImportError:
    _GENERATED_APPLICATION_VERSION = ""
    _GENERATED_SIDECAR_PACKAGE_VERSION = ""
    _GENERATED_SCIENCE_API_VERSION = ""
    _GENERATED_GIT_COMMIT = ""
    _GENERATED_DEPENDENCY_LOCK_SHA256 = ""


def _distribution_product_version() -> str:
    # In a source checkout prefer the single repository source of truth. This
    # also prevents a stale editable-install metadata directory from masking a
    # newer checkout during development and tests.
    root_package = Path(__file__).resolve().parents[3] / "package.json"
    try:
        value = json.loads(root_package.read_text(encoding="utf-8")).get("version")
        if isinstance(value, str) and value:
            return value
    except (OSError, ValueError, TypeError):
        pass
    try:
        return distribution_version("cortexlume-science")
    except PackageNotFoundError:
        return "unknown"


def _runtime_or_generated(name: str, generated: str, fallback: str) -> str:
    value = os.environ.get(name, "").strip()
    if value:
        return value
    if generated:
        return generated
    return fallback


def _source_lock_sha256() -> str:
    lock_path = Path(__file__).resolve().parents[3] / "pnpm-lock.yaml"
    try:
        return hashlib.sha256(lock_path.read_bytes()).hexdigest()
    except OSError:
        return "unknown"


_package_version = _distribution_product_version()
APPLICATION_VERSION = _runtime_or_generated(
    "CORTEXLUME_APP_VERSION", _GENERATED_APPLICATION_VERSION, _package_version,
)
SIDECAR_PACKAGE_VERSION = _runtime_or_generated(
    "CORTEXLUME_SIDECAR_PACKAGE_VERSION", _GENERATED_SIDECAR_PACKAGE_VERSION, _package_version,
)
# ``version`` is retained for clients built against the original health
# contract; the explicit fields above avoid conflating product and API versions.
__version__ = SIDECAR_PACKAGE_VERSION
SCIENCE_API_VERSION = _runtime_or_generated(
    "CORTEXLUME_SCIENCE_API_VERSION", _GENERATED_SCIENCE_API_VERSION, "1",
)
GIT_COMMIT = _runtime_or_generated("CORTEXLUME_GIT_COMMIT", _GENERATED_GIT_COMMIT, "unknown")
DEPENDENCY_LOCK_SHA256 = _runtime_or_generated(
    "CORTEXLUME_DEPENDENCY_LOCK_SHA256", _GENERATED_DEPENDENCY_LOCK_SHA256, _source_lock_sha256(),
)

BUILD_METADATA = {
    "applicationVersion": APPLICATION_VERSION,
    "sidecarPackageVersion": SIDECAR_PACKAGE_VERSION,
    "scienceApiVersion": SCIENCE_API_VERSION,
    "gitCommit": GIT_COMMIT,
    "dependencyLockSha256": DEPENDENCY_LOCK_SHA256,
}

__all__ = [
    "APPLICATION_VERSION",
    "BUILD_METADATA",
    "DEPENDENCY_LOCK_SHA256",
    "GIT_COMMIT",
    "SCIENCE_API_VERSION",
    "SIDECAR_PACKAGE_VERSION",
    "__version__",
]
